const demo=`int a = 10;
int b = 5;
int c;
c = a + b * 2;
int result;
result = c - 3;`;
const source=document.getElementById('sourceCode'), lineNumbers=document.getElementById('lineNumbers');
const tabContent=document.getElementById('tabContent'); let state={tokens:[],symbols:[],tac:[],quads:[],triples:[],ran:false};
source.value=demo;
document.getElementById('charCount').textContent=source.value.length+' chars';
function updateLines(){const n=source.value.split('\n').length;lineNumbers.textContent=Array.from({length:n},(_,i)=>i+1).join('\n')}
source.addEventListener('input',()=>{updateLines(); document.getElementById('charCount').textContent=source.value.length+' chars'}); source.addEventListener('scroll',()=>lineNumbers.scrollTop=source.scrollTop); updateLines();
document.getElementById('demoBtn').onclick=()=>{source.value=demo;updateLines();document.getElementById('charCount').textContent=source.value.length+' chars';run()};
document.getElementById('clearBtn').onclick=()=>{source.value='';updateLines();document.getElementById('charCount').textContent='0 chars';state={tokens:[],symbols:[],tac:[],quads:[],triples:[],ran:false};render()};
document.getElementById('runBtn').onclick=run;
document.getElementById('aboutBtn').onclick=()=>document.getElementById('aboutModal').classList.remove('hidden');
document.getElementById('closeModal').onclick=()=>document.getElementById('aboutModal').classList.add('hidden');
window.addEventListener('click',e=>{if(e.target.id==='aboutModal')e.target.classList.add('hidden')});
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');showTab(b.dataset.tab)});
const keywords=new Set(['int','if','else','while','return']); const ops=new Set(['+','-','*','/','%','<','>','=','==','!=','<=','>=']);
function tokenize(src){const out=[];let i=0,line=1;while(i<src.length){let c=src[i];if(/\s/.test(c)){if(c==='\n')line++;i++;continue}if(/[A-Za-z_]/.test(c)){let s='';while(i<src.length&&/[A-Za-z0-9_]/.test(src[i]))s+=src[i++];out.push({lexeme:s,type:keywords.has(s)?'KEYWORD':'IDENTIFIER',line});continue}if(/[0-9]/.test(c)){let s='';while(i<src.length&&/[0-9]/.test(src[i]))s+=src[i++];out.push({lexeme:s,type:'NUMBER',line});continue}let two=src.slice(i,i+2);if(['<=','>=','==','!='].includes(two)){out.push({lexeme:two,type:'OPERATOR',line});i+=2;continue}if('+-*/%=<>'.includes(c)){out.push({lexeme:c,type:'OPERATOR',line});i++;continue}if(';(){}'.includes(c)){out.push({lexeme:c,type:'DELIMITER',line});i++;continue}i++}return out}
function symbolsFrom(t){const s=[];for(let i=0;i<t.length;i++){if(t[i].lexeme==='int'&&t[i+1]&&t[i+1].type==='IDENTIFIER'){const n=t[i+1].lexeme;if(!s.some(x=>x.name===n))s.push({name:n,type:'int',scope:'global/block',value:'—'})}}return s}
function splitStatements(src){return src.replace(/\n/g,' ').split(';').map(x=>x.trim()).filter(Boolean)}
function precedence(op){return ({'==':1,'!=':1,'<':2,'>':2,'<=':2,'>=':2,'+':3,'-':3,'*':4,'/':4,'%':4})[op]||0}
function exprTokens(s){return (s.match(/[A-Za-z_][A-Za-z0-9_]*|\d+|<=|>=|==|!=|[()+\-*/%<>]/g)||[])}
function makeTac(src){let tac=[],temp=1;const emit=(op,a,b,r)=>tac.push({no:tac.length+1,op,a,b,r});function expr(e){let toks=exprTokens(e), vals=[],ops=[];function flush(){const op=ops.pop(),b=vals.pop(),a=vals.pop(),r=`t${temp++}`;emit(op,a,b,r);vals.push(r)}for(let x of toks){if(/^\w+$/.test(x)){vals.push(x)}else if(x==='('){ops.push(x)}else if(x===')'){while(ops.length&&ops.at(-1)!=='(')flush();ops.pop()}else{while(ops.length&&ops.at(-1)!=='('&&precedence(ops.at(-1))>=precedence(x))flush();ops.push(x)}}while(ops.length)flush();return vals.pop()||''}for(const st of splitStatements(src)){let m=st.match(/^int\s+([A-Za-z_]\w*)\s*(?:=\s*(.+))?$/);if(m){if(m[2]){const r=expr(m[2]);emit('=',r,'',m[1])}continue}m=st.match(/^([A-Za-z_]\w*)\s*=\s*(.+)$/);if(m){const r=expr(m[2]);emit('=',r,'',m[1])}}return tac}
function buildIR(tac){const q=tac.map((x,i)=>({no:i+1,op:x.op,arg1:x.a,arg2:x.b,result:x.r}));const tr=tac.map((x,i)=>({no:i,op:x.op,arg1:producerRef(x.a,i,tac),arg2:producerRef(x.b,i,tac)}));return {q,tr}}
function producerRef(v,i,t){if(!/^t\d+$/.test(v||''))return v||'';const p=t.findIndex((x,j)=>j<i&&x.r===v);return p>=0?`(${p})`:v}
function run(){const src=source.value.trim();if(!src){alert('Please enter a source program first.');return}state.tokens=tokenize(src);state.symbols=symbolsFrom(state.tokens);state.tac=makeTac(src);const ir=buildIR(state.tac);state.quads=ir.q;state.triples=ir.tr;state.ran=true;document.getElementById('tokenCount').textContent=state.tokens.length;document.getElementById('symbolCount').textContent=state.symbols.length;document.getElementById('tacCount').textContent=state.tac.length;document.getElementById('resultMessage').textContent='Analysis completed successfully. Select a tab to inspect each stage.';showTab('overview')}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function table(headers,rows){return `<table class="data-table"><thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.length?rows.map(r=>`<tr>${r.map(c=>`<td>${c}</td>`).join('')}</tr>`).join(''):`<tr><td colspan="${headers.length}">No data generated.</td></tr>`}</tbody></table>`}
function showTab(tab){if(!state.ran){tabContent.innerHTML=`<div class="empty"><div><div class="empty-icon">IC</div><b>Ready for analysis</b><div>Enter a source program and click <b>Generate Intermediate Code</b>.</div></div></div>`;return}if(tab==='overview'){tabContent.innerHTML=`<div class="overview"><div class="overview-box"><div class="big">${state.tokens.length}</div><small>Lexical tokens</small></div><div class="overview-box"><div class="big">${state.symbols.length}</div><small>Declared symbols</small></div><div class="overview-box"><div class="big">${state.tac.length}</div><small>TAC instructions</small></div><div class="overview-box"><div class="big">${state.quads.length}</div><small>Quadruples</small></div><div class="flow"><span>Source</span><i>→</i><span>Lexical Analysis</span><i>→</i><span>Symbol Table</span><i>→</i><span>Three Address Code</span><i>→</i><span>Quadruples / Triples</span></div></div>`}else if(tab==='tokens'){tabContent.innerHTML=table(['#','Lexeme','Type','Line'],state.tokens.map((x,i)=>[i+1,`<code>${esc(x.lexeme)}</code>`,`<span class="badge">${x.type}</span>`,x.line]))}else if(tab==='symbols'){tabContent.innerHTML=table(['#','Name','Type','Scope'],state.symbols.map((x,i)=>[i+1,`<code>${x.name}</code>`,x.type,x.scope]))}else if(tab==='tac'){tabContent.innerHTML=`<div class="code-list">${state.tac.map((x,i)=>`<span class="code-line"><span class="code-no">${i+1}</span>${esc(x.r+' = '+(x.op==='='?x.a:(x.a+' '+x.op+' '+x.b)))}</span>`).join('')}</div>`}else if(tab==='quad'){tabContent.innerHTML=table(['#','Operator','Arg 1','Arg 2','Result'],state.quads.map(x=>[x.no,`<code>${esc(x.op)}</code>`,`<code>${esc(x.arg1)}</code>`,`<code>${esc(x.arg2)}</code>`,`<code>${esc(x.result)}</code>`]))}else if(tab==='triples'){tabContent.innerHTML=table(['#','Operator','Arg 1','Arg 2'],state.triples.map(x=>[x.no,`<code>${esc(x.op)}</code>`,`<code>${esc(x.arg1)}</code>`,`<code>${esc(x.arg2)}</code>`]))}}
render(); function render(){document.getElementById('tokenCount').textContent=state.ran?state.tokens.length:0;document.getElementById('symbolCount').textContent=state.ran?state.symbols.length:0;document.getElementById('tacCount').textContent=state.ran?state.tac.length:0;showTab('overview')}

const heroRun=document.getElementById('heroRun'); if(heroRun) heroRun.onclick=()=>{source.value=demo;updateLines();document.getElementById('charCount').textContent=source.value.length+' chars';document.getElementById('runBtn').click();document.getElementById('workspace').scrollIntoView({behavior:'smooth',block:'start'});}; const heroScroll=document.getElementById('heroScroll'); if(heroScroll) heroScroll.onclick=()=>document.getElementById('workspace').scrollIntoView({behavior:'smooth',block:'start'});
